### ISSUE TITLE
add PB-MTL evaluation

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/pgmtl-data-release#5]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/12039957/85312233-8a77a100-b484-11ea-83ba-19a1ad7186f9.png">

pball_evaluation.csv has 145 lakes (likely the original source lakes tested on themselves), but should we also have the PB transfer learning results for the 305 (or more) lakes?

**Comment by jordansread** [comment]
yes, those will be coming in hopefully today. The tricky part with the PB-MTLs is that they have to extend the depths to match the target lake, which is a new processing step I haven't yet added here. But soon!
